export const defaultTheme = {
  lineHeight: {
    xxs: '100%',
    xs: '115%',
    sm: '120%',
    md: '133%',
    lg: '150%',
    xl: '175%',
  },
  letterSpacing: {
    default: '0px',
    sm: '-1px',
    md: '-2px',
    lg: '-3px',
  },
  fontSize: {
    xxxs: '12px',
    xxs: '14px',
    xs: '16px',
    sm: '20px',
    md: '24px',
    lg: '32px',
    xl: '40px',
    xxl: '48px',
    xxxl: '64px',
  },
  borderRadius: {
    none: '0px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    pill: '500px',
    circular: '50%',
  },
  borderWidths: {
    none: '0px',
    hairline: '1px',
    thin: '2px',
    thick: '4px',
    heavy: '8px',
  },
  spacingInline: {
    quarck: '4px',
    nano: '8px',
    xxxs: '16px',
    xxs: '24px',
    xs: '32px',
    sm: '40px',
    md: '48px',
    lg: '64px',
    xl: '80px',
  },
  spacingStack: {
    quarck: '4px',
    nano: '8px',
    xxxs: '16px',
    xxs: '24px',
    xs: '32px',
    sm: '40px',
    md: '48px',
    lg: '56px',
    xl: '64px',
    xxl: '80px',
    xxxl: '120px',
    huge: '160px',
    giant: '200px',
  },
  fontWeight: {
    extrabold: 800,
    bold: 700,
    semibold: 600,
    medium: 400,
    regular: 300,
  },
  brandColors: {
    primaryLight: '#F3C96F',
    primaryMain: '#F1BC4B',
    primaryDark: '#A88334',
    primaryContrast: '#211E1E',
    primaryBackground: '#FDF4E3',

    secondaryLight: '#F38F6F',
    secondaryMain: '#F1734B',
    secondaryDark: '#A85034',
    secondaryContrast: '#211E1E',
    secondaryBackground: '#FDE9E3',

    tertiaryLight: '#9E604C',
    tertiaryMain: '#863920',
    tertiaryDark: '#5D2716',
    tertiaryContrast: '#F0EFEE',
    tertiaryBackground: '#F4E5E1',
  },
  feedbackColors: {
    errorLight: '#EF5350',
    errorMain: '#D32F2F',
    errorDark: '#C62828',
    errorContrast: '#FFFFFF',
    errorBackground: '#FFDDEE',

    successLight: '#4CAF50',
    successMain: '#2E7D32',
    successDark: '#1B5E20',
    successContrast: '#FFFFFF',
    successBackground: '#EDF7ED',

    warningLight: '#FF9800',
    warningMain: '#ED6C02',
    warningDark: '#E65100',
    warningContrast: '#211E1E',
    warningBackground: '#FFF4E5',

    infoLight: '#03A9F4',
    infoMain: '#0288D1',
    infoDark: '#01579B',
    infoContrast: '#FFFFFF',
    infoBackground: '#E5F6FD',
  },
  baseColors: {
    darkSecondary: '#565454',
    darkMain: '#333333',
    darkHighlight: '#211E1E',
    darkContrast: '#FFFFFF',
    darkDisabled: '#AEAEAE',

    lightSecondary: '#F5F5F5',
    lightMain: '#EDEDED',
    lightHighlight: '#D6D5D5',
    lightContrast: '#FFFFFF',
  },
  backgroundColors: {
    'background-01': '#FFFFFF',
  },
}
